-- Read-only reconciliation audit trail for Cloudflare Cron supervision.
CREATE TABLE IF NOT EXISTS public.reconciliation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source TEXT NOT NULL DEFAULT 'cloudflare_cron_read_only',
    db_open_count INTEGER NOT NULL DEFAULT 0,
    exchange_open_count INTEGER NOT NULL DEFAULT 0,
    occupied_slot_count INTEGER NOT NULL DEFAULT 0,
    finding_count INTEGER NOT NULL DEFAULT 0,
    findings JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reconciliation_runs_checked_at
    ON public.reconciliation_runs (checked_at DESC);

ALTER TABLE public.reconciliation_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.reconciliation_runs FROM anon, authenticated;
GRANT SELECT ON TABLE public.reconciliation_runs TO authenticated;
